### ISSUE TITLE
Some android devices using Chrome Browser are not able to receive millicast stream

### ISSUE THREAD

**Issue by CastriOnlive** [millicast/millicast-sdk#128] opened 2021-12-06 21:49 UTC
**Version affected**
v0.1.16

**Describe the bug**
It is not possible to receive the Millicast View stream using this SDK for certain devices

**To Reproduce**
1. Publish an Stream with Millicast Publish

```   
  const millicastPublish = new Publish(streamName, tokenGenerator);
  this.millicastPublish = millicastPublish;
  const broadcastOptions = {
      mediaStream: stream,
      simulcast: true,
      disableAudio: false,
      diableVideo: false,
      bandwidth: 0,
      codec: 'h264'
  }
  //Start broadcast
  return millicastPublish.connect(broadcastOptions)
```

2. Receive the Stream with Millicast View
  `//Millicast View 
    const tokenGenerator = () => Director.getSubscriber(streamName, accountId)
    const millicastView = new View(streamName, tokenGenerator, null, true);`

3. Use a Samsung Galaxy A12 with Chrome 96 version to receive the stream.
4. Check that the video is received well.

**Expected behavior**
It should be possible to receive the media stream and watch the video.

**Environment:**
 - OS: Android
 - Device: Samsung Galaxy A12, SM-A125F/DSN
 - Browser Chrome
 - Version 96.0.4664.45

**Additional context**
**NOTE:** Other devices are not able to receive the Millicast signal, but we have not collected information on user agent. It would be really nice if you could give us a list of requirements on devices that are proven to work using Millicast SDK.

**Comment by R-Delfino95** [comment] 2021-12-15 18:57
Hi @CastriOnlive, we tried to reproduce using a similar device (Galaxy A11 and same browser version) but it's working.
We have pending to make a list of compatible devices/browsers, for now we tested using Chrome Desktop and from version `76.0.3809.100` and beyond should work (not sure but it should apply to the Chrome mobile version too).

If you can replicate the issue using a mobile phone, you can help us showing the SDK Logger and sending us a screen capture if it's throwing a console.error or the full log in a txt file.
To enable the SDK logs, you can import the `Logger` module and then you can enable the logs in console using `Logger.setLevel(Logger.DEBUG)`, more info [here.](https://millicast.github.io/millicast-sdk/Logger.html#.setLevel)
Then you can connect your mobile into a PC, go to the page you are using the SDK and start a [remote debugging](https://developer.chrome.com/docs/devtools/remote-debugging/) so you can see the logs in the console.
To print all the logs you can use `.getHistory()` method, more info [here.](https://millicast.github.io/millicast-sdk/Logger.html#.getHistory)

**Comment by rnkvogel** [comment] 2021-12-20 17:22
Mozilla/5.0 (Linux; Android 11; SM-A326U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.104 Mobile Safari/537.36  Debugging has no errors on console. SDP offer is created. Tested Chrome Canary no errors. Screen is black for playback Chrome. Millicast publisher on Chrome will show as publishing. Codec VP8 and H264 has the same result.   NOTE. Millicast publisher and playback on the SM-A326U will work on Firefox 95.

**Comment by CastriOnlive** [comment] 2021-12-21 21:26
> 

I will try to check the logs asap

**Comment by CastriOnlive** [comment] 2021-12-22 15:47
[viewer.millicast.com-1640166319621.log](https://github.com/millicast/millicast-sdk/files/7763662/viewer.millicast.com-1640166319621.log)
![image (1)](https://user-images.githubusercontent.com/85135004/147118659-b9ba5cbf-a765-4d26-b35c-5f792ba5a610.png)
These logs are using millicast viewer directly with the specified device.

**Comment by murillo128** [comment] 2022-01-11 09:29
can you try with latest SDK and copy&paste the full console logs instead of just an screenshoot?

**Comment by CastriOnlive** [comment] 2022-01-14 16:43
I already updated to 0.1.20
It still happens, here are the logs

`
[log.txt](https://github.com/millicast/millicast-sdk/files/7871875/log.txt)
`

**Comment by murillo128** [comment] 2022-02-11 19:05
btw, forgot to update the ticket, but it is a chrome issue, webrtc is not working on certain devices:

https://bugs.chromium.org/p/chromium/issues/detail?id=1240237&q=&can=5

Will keep this bug open to notify when the issue is resolved in chrome

**Comment by murillo128** [comment] 2022-03-04 20:46
should be fixed in latest chrome release

**Closed by murillo128** 2022-03-04 20:46 UTC
Labels: bug
