### ISSUE TITLE
Unable to run the "Millicast Viewer Demo"

### ISSUE THREAD

**Issue by bigbean17** [millicast/millicast-sdk#376] opened 2024-06-19 00:43 UTC
I followed the README but it keeps throwing me the error of "The "bootstrap" command was removed by default in v7, and is no longer maintained'

According to the doc https://lerna.js.org/docs/legacy-package-management#replacing-your-usage-of-lerna-bootstraplerna-link, I replaced `lerna bootstrap` but still unable to run. 

Any help would be appreciated. Thank you

**Comment by Santiago-Souto** [comment] 2024-06-27 20:07
Hey @bigbean17 ! Thanks for reporting this. Could you give us more information on steps to reproduce that issue?

**Comment by matthewclickbid** [comment] 2024-07-01 20:49
Steps to reproduce for me:
Mac Sonoma 14.2.1
Download millicast-sdk
Open terminal into millicast-view-demo
Run sudo npm ci
Receive error
ERR! bootstrap The "bootstrap" command was removed by default in v7, and is no longer maintained.
ERR! bootstrap Learn more about this change at https://lerna.js.org/docs/legacy-package-management
npm error code 1
npm error path /Users/matthewburnell/Desktop/folder
npm error command failed
npm error command sh -c lerna bootstrap --ci

**Comment by Santiago-Souto** [comment] 2024-07-02 16:11
Ok, if that is the steps for @bigbean17 as well, the issue is the location were the modules installation is done. That command should be done from root directory (path/to/millicast-sdk) not inside any of the packages directories. I'll close the issue, but if those were not the same steps to reproduce it, please comment or reopen the issue.

Thanks!

**Closed by Santiago-Souto** 2024-07-02 16:11 UTC
Labels: question

**Comment by matthewclickbid** [comment] 2024-07-04 02:03
@Santiago-Souto this worked for me as well.

**Comment by vitaly-castLabs** [comment] 2024-09-17 10:03
This is confusing. So this is wrong? https://github.com/millicast/millicast-sdk/blob/main/packages/millicast-viewer-demo/README.md?plain=1#L24 - if so, shouldn't it be fixed before closing the issue?
